#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.
ARG BUILD_VERSION=Dev

FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
ARG BUILD_VERSION

WORKDIR /app
EXPOSE 80
EXPOSE 443


FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
ARG BUILD_VERSION

WORKDIR /src
COPY ["nuget.config", "."]
COPY ["CNIParser.csproj", "."]
RUN dotnet restore "CNIParser.csproj"
COPY . .
RUN dotnet build "CNIParser.csproj" -c Release -o /app/build

FROM build AS publish
ARG BUILD_VERSION
RUN dotnet publish "CNIParser.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
ARG BUILD_VERSION

WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "CNIParser.dll"]

ENV BUILD_VERSION $BUILD_VERSION